#! /bin/bash
function func {
CROSS="^ib(1)x^p(-11)^co(15)^p(-2)"
DZENLINE=()
DZENLINE[1]="^ca(1, devmon -u ) ExtUSB^ca()"
DZENLINE[0]="^ca(1,  wicd-client) Wifi ^ca()^ca(1, wmctrl -c wicd) $CROSS^ca() "
DZENLINE[2]="^ca(1, systemctl poweroff -i ) Apagar ^ca()"
echo "${DZENLINE[*]}"
}
sleep 0.1; func | dzen2 -y -1 -title-name dzenb  -ta center -bg "#224466" -expand left -e '' -fn lat2-10 -p 
