#! /bin/bash
function func {
DZENLINE=()
DZENLINE[1]="^ca(1, devmon -u ) ExtraerPendrive^ca()"
DZENLINE[0]="^ca(1,  wicd-client) Wifi^ca()"
DZENLINE[2]="^ca(1, urxvt -g +438+17 +sb -e alsamixer ) Audio^ca()"
DZENLINE[3]="^ca(1, systemctl poweroff -i ) ApagarPC ^ca()"
echo "${DZENLINE[*]}"
}
func | dzen2 -x 658 -w 366 -title-name dzenb  -ta center -bg "#224466" -expand left -e 'entertitle=exec:;leavetitle=exec:' -p
