#!/bin/bash
system_screen_resolution="$(xrandr | sed -n '/*/p' | awk '{print$1}')"
xres="$(echo $system_screen_resolution | awk -F 'x' '{print$1}')"
yres="$(echo $system_screen_resolution | awk -F 'x' '{print$2}')"
x1="$(echo "$xres*3/4"  | bc -l)"
x2=${x1%.*}

function func {
DZENLINE=()
DZENLINE[0]="^ca(1, firefox ) Navegador de Internet ^ca()\n"
DZENLINE[1]="^ca(1, thunar ) Gestor de Archivos ^ca()\n"
DZENLINE[2]="^ca(1, mirage $HOME/Pictures/ ) Galeria de Imagenes ^ca()\n"
DZENLINE[3]="^ca(1, vlc ) Reproductor Multimedia ^ca()"
echo -e "${DZENLINE[*]}"
}
func | dzen2 -w $x2 -m h -l 4  -fn lat2-10 -y $yres -title-name dzenc -ta center -bg "#224466" -p -sa center -e ''
