#!/bin/bash
system_screen_resolution="$(head -n 1 /sys/class/drm/card0/card0-DVI-I-1/modes | awk -F 'x' '{print$1}')"
bar="$( echo "$system_screen_resolution*3/4"  | bc -l)"
bar2=${bar%.*}
function audio {
DZENLINE=()
DZENLINE[0]="^ca(1, amixer -q set Master unmute & amixer -q set LFE unmute & amixer -q set PCM 7%- ) < ^ca()\n"
DZENLINE[1]="^ca(1, amixer -q set Master unmute & amixer -q set LFE unmute & amixer -q set PCM 7%+ ) >  ^ca()\n"
DZENLINE[2]="^ca(1, amixer -q set Master toggle & amixer -q set LFE toggle ) x ^ca()"
echo -e "${DZENLINE[*]}"
}
audio | dzen2 -w 60 -x $(($bar2+10)) -m h -l 3  -fn lat2-10 -y -1 -title-name dzend -bg "#224466" -p -sa center -e ''
