#!/bin/bash
read -p "Write the number for the boot (/dev/sdaX) partition: " x
parted /dev/sda toggle '$x' boot
pacstrap /mnt base git iw dialog wpa_supplicant grub vim os-prober
genfstab -U /mnt >> /mnt/etc/fstab 
cp /root/xmonad-lightconfig/.scripts/install_arch2 /mnt/root/
arch-chroot /mnt
