#!/bin/bash
system_screen_resolution="$(xrandr | sed -n '/*/p' | awk '{print$1}' | sed -n '1 p' )"
xres="$(echo $system_screen_resolution | awk -F 'x' '{print$1}')"
yres="$(echo $system_screen_resolution | awk -F 'x' '{print$2}')"
x1="$(echo "$xres*3/4"  | bc -l)"
x2=${x1%.*}

function func {
DZENLINE=()
DZENLINE[0]="^ca(1, xdotool keydown Alt key f keyup Alt ) Navegador de Internet ^ca()\n"
DZENLINE[1]="^ca(1, xdotool keydown Alt key a keyup Alt ) Gestor de Archivos ^ca()\n"
DZENLINE[2]="^ca(1, mirage $HOME/Pictures/ ) Galeria de Imagenes ^ca()\n"
DZENLINE[3]="^ca(1, vlc ) Reproductor Multimedia\n ^ca()"
DZENLINE[4]="^ca(1, gimp ) Editor de Imagenes\n ^ca()"
DZENLINE[5]="^ca(1, libreoffice ) LibreOffice ^ca()"
echo -e "${DZENLINE[*]}"
}
func | dzen2 -w $x2 -m h -l 6  -fn lat2-10 -y $yres -title-name dzenc -ta center -bg "#224466" -p -sa center 
