#! /bin/bash
FONT=Arial
export BG="#224466"
export FG="#999999"

function func {
i=0
while true;
do
i=0
CMD="wmctrl -ia "
CMDx="wmctrl -ic "

#CROSS="^ib(1)x^p(-11)^co(15)^p(-2)"
CROSS="^fg(red)X"
WINDOWS=($(wmctrl -l | sort -n | awk '{print$4$5$6}' | tr "\n" " ")) 
WINDOWS2=($(wmctrl -xl | sort -n | awk '{print$3}' | sed 's/\([0-Z]*\).[0-Z]*/\1/g' | tr "\n" " ")) 
WINDOWS_ID=($(wmctrl -xl | sort -n | awk '{print$1}' | tr "\n" " "))
CURRENT_WORKSPACE="$(wmctrl -d | sed '/\*/!d' | awk '{print$1}')"
CURRENT_WINDOW_ID="$(wmctrl -l | sed '/[0-f]\ \ '$CURRENT_WORKSPACE'\ /!d' | tail -n 1 | awk '{print$1}')"
CURRENT_WINDOW_TITLE="$(wmctrl -xl | sed '/[0-f]\ \ '$CURRENT_WORKSPACE'\ /!d' | tail -n 1 | awk '{print$3}' | sed 's/\([0-Z]*\).[0-Z]*/\1/g' )"
LENGTH="${#WINDOWS[*]}"
while [ "$i" -le "$LENGTH" ]
do
		DZENLINE["$i"]="^ca(1, $CMD ${WINDOWS_ID["$i"]})${WINDOWS2["$i"]} "${WINDOWS["$i"]}"^ca()"
		if [ -n "${WINDOWS["$i"]}" ]; then 
				DZENLINE["$i"]+="^ca(1, $CMDx ${WINDOWS_ID["$i"]}) $CROSS^ca()"
			#the last value in this array is the focused window, it's highlighted
			if [ "${WINDOWS_ID["$i"]}" = "$CURRENT_WINDOW_ID"  ]; then
				DZENLINE["$i"]="^fg(#224466)^bg(#999999)${DZENLINE["$i"]}"
			else
				DZENLINE["$i"]="^bg(#224466)^fg(#999999)${DZENLINE["$i"]}"
			fi
		fi
	i=$(($i+1))
done
i=0
echo "${DZENLINE[*]} "
DZENLINE=()
sleep 1;
done;
}

func | dzen2 -title-name dzend -ta center -bg "#224466" -expand left -e '' -fn lat2-10 

#install "wmctrl" from the official repositories
#add this to make work "wmctrl" in xmonad
#import XMonad.Hooks.EwmhDesktops
#main = xmonad $ ewmh defaults
#add this to your xmonad.hs file to make space in your screen
# manageHook = manageDocks <+> [whatever you had before]]
#myLayout =      avoidStruts $
#		[whatever you had before]
