#!/bin/sh
dmodeVGA="$(cat /sys/class/drm/card0-VGA-1/status)"
dmodeHDMI="$(cat /sys/class/drm/card0-HDMI-A-1/status)"
HDMIresolution="$(cat /sys/class/drm/card0-HDMI-A-1/modes | head -n 1)"
VGAresolution="$(cat /sys/class/drm/card0-VGA-1/modes | head -n 1)"
export DISPLAY=:0.0

if [ "${dmodeVGA}" = connected ] && [ "${dmodeHDMI}" = disconnected ]; then
	xrandr --output VGA-0 --mode "$VGAresolution" --auto --output LVDS --off --output HDMI-0 --off
	echo	"defaults.pcm.card 0" > $HOME/.asoundrc
	#0 will enable VGA audio output
	echo	"defaults.pcm.device 0" >> $HOME/.asoundrc
	echo	"defaults.ctl.card 0" >> $HOME/.asoundrc
fi

if [ "${dmodeVGA}" = disconnected ] && [ "${dmodeHDMI}" = connected ]; then

echo	"defaults.pcm.card 1" > $HOME/.asoundrc
#3 will enable HDMI audio output
echo	"defaults.pcm.device 3" >> $HOME/.asoundrc
echo	"defaults.ctl.card 0" >> $HOME/.asoundrc

	xrandr --output HDMI-0 --mode "1024x768" --auto
	xrandr --output LVDS --off
	xrandr --output VGA-0 --off
fi
notify-send "VGA -- $dmodeVGA /// HDMI -- $dmodeHDMI" 
