#!/bin/bash
system_screen_resolution="$(xrandr | sed -n '/*/p' | awk '{print$1}' | sed -n '1 p' )"
if [ ! -d $HOME/Pictures ]; then mkdir $HOME/Pictures; fi;
if [ ! -d $HOME/Pictures/wallpapers ]; then mkdir $HOME/Pictures/wallpapers; fi;
echo "loading a fully new random wallpaper,be ready..."
DATE=`date +%H%M%S`
wget `wget http://wallpaperstock.net/random-wallpapers.html -q -O - | grep  "<a  href='/" |  sed 's/.*href=.*\/\(.*\).html.*/http:\/\/wallpaperstock.net\/\1.html/g' | shuf -n1 | sed 's/_w\([0-9].*\).html/_\1_'$system_screen_resolution'.jpg/'` -O $HOME/Pictures/wallpapers/wallpaper$DATE.jpg 
PIC=$HOME/Pictures/wallpapers/wallpaper$DATE.jpg
if [ -s $HOME/Pictures/wallpapers/wallpaper$DATE.jpg ]; 
then 
cp $HOME/Pictures/wallpapers/wallpaper$DATE.jpg $HOME/.background.jpg
else
echo "Download failed. Setting an stored one"
PIC="$(ls $HOME/Pictures/wallpapers/ | shuf | tail -n 1)"
cp $HOME/Pictures/wallpapers/$PIC $HOME/.background.jpg
fi
hsetroot -center $HOME/.background.jpg
read -p "Press enter to close..."
