#! /bin/bash
#Wait 10 seconds and update pacamanupdate script (loaded by pacman-update.serice)
sleep 10
cp /home/user/.scripts/init_services/pacmanupdate /root/pacmanupdate
#Wait 200 seconds to be sure that internet connection has been stablished 
sleep 200
#Backup mirrorlist
cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup 
#Update mirror list, get 10 latest updated mirrors, then keep the 5 fastest and sort them by "rate"
reflector --verbose -l 10 -f 5 --sort rate --save /etc/pacman.d/mirrorlist
#Reflesh packages and update system
pacman -Syu --noconfirm
#Remove older downloaded packages, keep the system memory usage lightweith
pacman -Sc --noconfirm
#Remove orphaned installed packages
if [[ ! -n $(pacman -Qdt) ]]; then
	echo "No orphans to remove."
	else
pacman -Rns --noconfirm $(pacman -Qdtq)
fi
