#! /bin/bash
FILES="/home/user/.scripts/init_services"
ufw default deny
ufw allow from 192.168.0.0/24
ufw allow Deluge
#ufw has the ability to deny connections from an IP address that has attempted to initiate 6 or more connections in the last 30 seconds. Users should consider using this option for services such as sshd. 
ufw allow SSH
ufw limit SSH
ufw enable
systemctl disable getty\@tty1.service
rm -R /etc/systemd/system/getty\@tty1.service.d/autologin.conf
cat $FILES/getty\@tty1.service.d/autologin.conf | sed 's/root/user/' > /etc/systemd/system/getty\@tty1.service.d/autologin.conf
cp -f $FILES/sudoers /etc/
cp $FILES/pacmanupdate /root/
cp $FILES/pacman-update.service /etc/systemd/system/
systemctl enable ufw
systemctl enable wicd
systemctl enable getty\@tty1.service
systemctl enable pacman-update.service
read -p "press enter to reset services" 
systemctl restart /etc/systemd/system/getty\@tty.service.d
